assets:
  - randyfay.sql.gz
  - files.tgz
steps:
  - name: Load files
    plugin: Shell
    command: 'cd $SRC_DIR/sites/default && tar -zxf $ASSET_DIR/files.tgz'
  - name: Probo.CI site setup
    plugin: Drupal
    database: randyfay.sql.gz
    databaseGzipped: true
    databaseUpdates: true
    clearCaches: true
