<?php
// $Id$

/**
 * @file
 * Provides install, updated, and uninstall functions for recaptcha.
 */

/**
 * Implements hook_uninstall().
 */
function recaptcha_uninstall() {
  // Delete all the recaptcha variables and then clear the variable cache
  //db_query("delete from {variable} where name like '%s'", 'recaptcha_%');
  db_delete('variable')
    ->condition('name', 'recaptcha_%', 'LIKE')
    ->execute();
  cache_clear_all('variables', 'cache');
}